version: "3"
services:
  website:
    build:
      context: ./
    ports:
      - "8080:80"
      - "443:443"
    #tty: true
    #stdin_open: true
    #command: bash
    #volumes:
    #  - ./ssl:/usr/local/apache2/conf/

  #openvpn:
  #  cap_add:
  #   - NET_ADMIN
  #  image: kylemanna/openvpn
  #  container_name: openvpn
  #  ports:
  #   - "1194:1194/udp"
  #  restart: always
  #  volumes:
  #   - /root/network/openvpn:/etc/openvpn
